// Generated by Scripts/regenerate-provider-manifests.sh. Do not edit by hand.
import CodexBarCore
import Foundation

/// Closed catalog of providers supported by this QuotaKit build.
enum ProviderImplementationManifest {
    static let makeImplementations: [@Sendable () -> any ProviderImplementation] = [
        { CodexProviderImplementation() },
        { ClaudeProviderImplementation() },
        { CursorProviderImplementation() },
        { GrokProviderImplementation() },
    ]
}
