#!/usr/bin/env bash
set -euo pipefail
CONF=${1:-release}
ALLOW_LLDB=${CODEXBAR_ALLOW_LLDB:-0}
SIGNING_MODE=${CODEXBAR_SIGNING:-}
ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
LOWER_CONF=$(printf "%s" "$CONF" | tr '[:upper:]' '[:lower:]')

# Load version info
source "$ROOT/version.env"
if [[ -f "$ROOT/.mac-release.env" ]]; then
  source "$ROOT/.mac-release.env"
fi

APP_DISPLAY_NAME="${MAC_RELEASE_APP_NAME:-QuotaKit}"
APP_EXECUTABLE_NAME="${MAC_RELEASE_APP_EXECUTABLE:-QuotaKit}"
APP_BUNDLE_NAME="${APP_DISPLAY_NAME}.app"
APP_SWIFTPM_PRODUCT="${MAC_RELEASE_APP_SWIFTPM_PRODUCT:-CodexBar}"
CLI_SWIFTPM_PRODUCT="${MAC_RELEASE_CLI_SWIFTPM_PRODUCT:-CodexBarCLI}"
CLI_EXECUTABLE_NAME="${MAC_RELEASE_CLI_EXECUTABLE:-QuotaKitCLI}"
WATCHDOG_SWIFTPM_PRODUCT="${MAC_RELEASE_WATCHDOG_SWIFTPM_PRODUCT:-CodexBarClaudeWatchdog}"
WATCHDOG_EXECUTABLE_NAME="${MAC_RELEASE_WATCHDOG_EXECUTABLE:-QuotaKitClaudeWatchdog}"
WIDGET_PRODUCT_NAME="${MAC_RELEASE_WIDGET_PRODUCT_NAME:-QuotaKitWidget}"
WIDGET_EXTENSION_PROJECT_NAME="${MAC_RELEASE_WIDGET_PROJECT_NAME:-CodexBarWidgetExtension}"
WIDGET_EXTENSION_SCHEME="${MAC_RELEASE_WIDGET_SCHEME:-CodexBarWidgetExtension}"

# Clean build only when explicitly requested (slower).
if [[ "${CODEXBAR_FORCE_CLEAN:-0}" == "1" ]]; then
  if [[ -d "$ROOT/.build" ]]; then
    if command -v trash >/dev/null 2>&1; then
      if ! trash "$ROOT/.build"; then
        echo "WARN: trash .build failed; continuing with swift package clean." >&2
      fi
    else
      rm -rf "$ROOT/.build" || echo "WARN: rm -rf .build failed; continuing with swift package clean." >&2
    fi
  fi
  swift package clean >/dev/null 2>&1 || true
fi

# Build for host architecture by default; allow overriding via ARCHES (e.g., "arm64 x86_64" for universal).
ARCH_LIST=( ${ARCHES:-} )
if [[ ${#ARCH_LIST[@]} -eq 0 ]]; then
  HOST_ARCH=$(uname -m)
  case "$HOST_ARCH" in
    arm64) ARCH_LIST=(arm64) ;;
    x86_64) ARCH_LIST=(x86_64) ;;
    *) ARCH_LIST=("$HOST_ARCH") ;;
  esac
fi

patch_keyboard_shortcuts() {
  local util_path="$ROOT/.build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
  if [[ ! -f "$util_path" ]]; then
    return 0
  fi
  if grep -q "keyboardShortcutsSafeBundle" "$util_path"; then
    return 0
  fi

  chmod +w "$util_path" || true
  python3 - "$util_path" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()
if ".keyboardShortcutsSafeBundle" in text:
    sys.exit(0)

text = text.replace(
    'NSLocalizedString(self, bundle: .module, comment: self)',
    'NSLocalizedString(self, bundle: .keyboardShortcutsSafeBundle, comment: self)',
)

inject = """
private extension Bundle {
    /// Safe lookup that avoids the fatal trap in the autogenerated `Bundle.module`
    /// when the resource bundle is not placed at the bundle root.
    static let keyboardShortcutsSafeBundle: Bundle = {
        #if os(macOS)
        if let url = Bundle.main.url(forResource: "KeyboardShortcuts_KeyboardShortcuts", withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }

        let rootURL = Bundle.main.bundleURL.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }
        #endif

        let devURL = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()  // Utilities.swift
            .deletingLastPathComponent()  // KeyboardShortcuts
            .deletingLastPathComponent()  // Sources
            .appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: devURL) {
            return bundle
        }

        return Bundle.main
    }()
}
"""

marker = "}\n\n\nextension Data {"
if marker not in text:
    raise SystemExit("Marker not found in Utilities.swift; patch failed.")

text = text.replace(marker, "}\n\n" + inject + "\n\nextension Data {")
path.write_text(text)
PY
}

KEYBOARD_SHORTCUTS_UTIL="$ROOT/.build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
if [[ ! -f "$KEYBOARD_SHORTCUTS_UTIL" ]]; then
  swift build -c "$CONF" --arch "${ARCH_LIST[0]}"
fi
patch_keyboard_shortcuts

for ARCH in "${ARCH_LIST[@]}"; do
  swift build -c "$CONF" --arch "$ARCH"
done

# Build the app bundle in /tmp to avoid Dropbox adding resource forks during signing
APP_FINAL="$ROOT/${APP_BUNDLE_NAME}"
APP="/tmp/quotakit-build-$$/${APP_BUNDLE_NAME}"
STAGED_APP_PATH="${CODEXBAR_STAGED_APP_PATH:-}"
INSTALL_APP_PATH="${CODEXBAR_INSTALL_PATH:-}"
rm -rf "$APP_FINAL" "$(dirname "$APP")"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" "$APP/Contents/Frameworks"
mkdir -p "$APP/Contents/Helpers" "$APP/Contents/PlugIns"

# Convert new .icon bundle to .icns if present (macOS 14+/IconStudio export)
ICON_SOURCE="$ROOT/Icon.icon"
ICON_TARGET="$ROOT/Icon.icns"
if [[ -f "$ICON_SOURCE" ]]; then
  iconutil --convert icns --output "$ICON_TARGET" "$ICON_SOURCE"
fi

BUNDLE_ID="com.columbuslabs.quotakit.mac"
RELEASE_BRANCH="${QUOTAKIT_RELEASE_BRANCH:-${CODEXBAR_RELEASE_BRANCH:-main}}"
FEED_URL="${MAC_RELEASE_FEED_URL:-https://raw.githubusercontent.com/ColumbusLabs/QuotaKit/${RELEASE_BRANCH}/appcast.xml}"
AUTO_CHECKS=true
if [[ "$LOWER_CONF" == "debug" ]]; then
  BUNDLE_ID="com.columbuslabs.quotakit.mac.debug"
  FEED_URL=""
  AUTO_CHECKS=false
fi
if [[ "$SIGNING_MODE" == "adhoc" ]]; then
  FEED_URL=""
  AUTO_CHECKS=false
fi
SPARKLE_PUBLIC_ED_KEY="${SPARKLE_PUBLIC_ED_KEY:-${MAC_RELEASE_SUPUBLIC_ED_KEY:-}}"
if [[ "$LOWER_CONF" != "debug" && "$SIGNING_MODE" != "adhoc" ]]; then
  if [[ -z "$SPARKLE_PUBLIC_ED_KEY" || "$SPARKLE_PUBLIC_ED_KEY" == TODO_* ]]; then
    echo "ERROR: Set MAC_RELEASE_SUPUBLIC_ED_KEY in .mac-release.env or SPARKLE_PUBLIC_ED_KEY in the release environment." >&2
    exit 1
  fi
fi
WIDGET_BUNDLE_ID="${BUNDLE_ID}.widget"
# QuotaKit-owned signing/team values must be supplied by release env. The
# placeholder default prevents accidental packaging under upstream credentials.
APP_TEAM_ID="${APP_TEAM_ID:-${QUOTAKIT_TEAM_ID:-QUOTAKIT_TEAM_ID}}"
APP_GROUP_ID="group.com.columbuslabs.quotakit"
ICLOUD_KVS_ID="${QUOTAKIT_ICLOUD_KVS_ID:-${CODEXBAR_ICLOUD_KVS_ID:-${APP_TEAM_ID}.com.columbuslabs.quotakit.shared}}"
INCLUDE_SHARED_ENTITLEMENTS=1
if [[ "$BUNDLE_ID" == *".debug"* ]]; then
  APP_GROUP_ID="group.com.columbuslabs.quotakit.debug"
fi
if [[ "$SIGNING_MODE" == "adhoc" ]]; then
  INCLUDE_SHARED_ENTITLEMENTS=0
fi
ENTITLEMENTS_DIR="$ROOT/.build/entitlements"
APP_ENTITLEMENTS="${ENTITLEMENTS_DIR}/${APP_EXECUTABLE_NAME}.entitlements"
WIDGET_ENTITLEMENTS="${ENTITLEMENTS_DIR}/${WIDGET_PRODUCT_NAME}.entitlements"
mkdir -p "$ENTITLEMENTS_DIR"
if [[ "$ALLOW_LLDB" == "1" && "$LOWER_CONF" != "debug" ]]; then
  echo "ERROR: CODEXBAR_ALLOW_LLDB requires debug configuration" >&2
  exit 1
fi
# Determine if we need get-task-allow (Apple Development certs require it to launch)
NEEDS_GET_TASK_ALLOW=0
if [[ "$ALLOW_LLDB" == "1" ]]; then
  NEEDS_GET_TASK_ALLOW=1
elif [[ "$SIGNING_MODE" != "adhoc" ]]; then
  _EFFECTIVE_ID="${APP_IDENTITY:-}"
  if [[ "$_EFFECTIVE_ID" == "Apple Development:"* ]]; then
    NEEDS_GET_TASK_ALLOW=1
  fi
fi
cat > "$APP_ENTITLEMENTS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    $(if [[ "$INCLUDE_SHARED_ENTITLEMENTS" == "1" ]]; then cat <<EOF
<key>com.apple.application-identifier</key>
    <string>${APP_TEAM_ID}.${BUNDLE_ID}</string>
    <key>com.apple.developer.team-identifier</key>
    <string>${APP_TEAM_ID}</string>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>${APP_GROUP_ID}</string>
    </array>
    <key>com.apple.developer.ubiquity-kvstore-identifier</key>
    <string>${ICLOUD_KVS_ID}</string>
    <key>com.apple.developer.icloud-services</key>
    <array>
        <string>CloudKit</string>
    </array>
    <key>com.apple.developer.icloud-container-identifiers</key>
    <array>
        <string>iCloud.com.columbuslabs.quotakit</string>
    </array>
    <key>com.apple.developer.icloud-container-environment</key>
    <string>Production</string>
EOF
fi)
    $(if [[ "$NEEDS_GET_TASK_ALLOW" == "1" ]]; then echo "    <key>com.apple.security.get-task-allow</key>
    <true/>"; fi)
</dict>
</plist>
PLIST
cat > "$WIDGET_ENTITLEMENTS" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    $(if [[ "$INCLUDE_SHARED_ENTITLEMENTS" == "1" ]]; then cat <<EOF
<key>com.apple.security.application-groups</key>
    <array>
        <string>${APP_GROUP_ID}</string>
    </array>
EOF
fi)
</dict>
</plist>
PLIST
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>${APP_DISPLAY_NAME}</string>
    <key>CFBundleDisplayName</key><string>${APP_DISPLAY_NAME}</string>
    <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
    <key>CFBundleExecutable</key><string>${APP_EXECUTABLE_NAME}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${MARKETING_VERSION}</string>
    <key>CFBundleVersion</key><string>${BUILD_NUMBER}.${MOBILE_VERSION}</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><true/>
    <key>CFBundleIconFile</key><string>Icon</string>
    <key>NSHumanReadableCopyright</key><string>QuotaKit includes upstream CodexBar code. MIT License notices are preserved.</string>
    <key>SUFeedURL</key><string>${FEED_URL}</string>
    <key>SUPublicEDKey</key><string>${SPARKLE_PUBLIC_ED_KEY}</string>
    <key>SUEnableAutomaticChecks</key><${AUTO_CHECKS}/>
    <key>CodexMobileVersion</key><string>${MOBILE_VERSION}</string>
    <key>CodexBuildTimestamp</key><string>${BUILD_TIMESTAMP}</string>
    <key>CodexGitCommit</key><string>${GIT_COMMIT}</string>
    <key>CodexBarTeamID</key><string>${APP_TEAM_ID}</string>
</dict>
</plist>
PLIST

build_product_path() {
  local name="$1"
  local arch="$2"
  case "$arch" in
    arm64|x86_64) echo ".build/${arch}-apple-macosx/$CONF/$name" ;;
    *) echo ".build/$CONF/$name" ;;
  esac
}

# Resolve path to built binary; some SwiftPM versions use .build/$CONF/ when building for host only.
resolve_binary_path() {
  local name="$1"
  local arch="$2"
  local candidate
  candidate=$(build_product_path "$name" "$arch")
  if [[ -f "$candidate" ]]; then
    echo "$candidate"
    return
  fi
  if [[ "$arch" == "arm64" || "$arch" == "x86_64" ]] && [[ -f ".build/$CONF/$name" ]]; then
    echo ".build/$CONF/$name"
  fi
}

verify_binary_arches() {
  local binary="$1"; shift
  local expected=("$@")
  local actual
  actual=$(lipo -archs "$binary")
  local actual_count expected_count
  actual_count=$(wc -w <<<"$actual" | tr -d ' ')
  expected_count=${#expected[@]}
  if [[ "$actual_count" -ne "$expected_count" ]]; then
    echo "ERROR: $binary arch mismatch (expected: ${expected[*]}, actual: ${actual})" >&2
    exit 1
  fi
  for arch in "${expected[@]}"; do
    if [[ "$actual" != *"$arch"* ]]; then
      echo "ERROR: $binary missing arch $arch (have: ${actual})" >&2
      exit 1
    fi
  done
}

install_binary() {
  local name="$1"
  local dest="$2"
  local binaries=()
  for arch in "${ARCH_LIST[@]}"; do
    local src
    src=$(resolve_binary_path "$name" "$arch")
    if [[ -z "$src" || ! -f "$src" ]]; then
      echo "ERROR: Missing ${name} build for ${arch} at $(build_product_path "$name" "$arch")" >&2
      exit 1
    fi
    binaries+=("$src")
  done
  if [[ ${#ARCH_LIST[@]} -gt 1 ]]; then
    lipo -create "${binaries[@]}" -output "$dest"
  else
    cp "${binaries[0]}" "$dest"
  fi
  chmod +x "$dest"
  verify_binary_arches "$dest" "${ARCH_LIST[@]}"
}

ensure_widget_extension_project() {
  local spec="$ROOT/WidgetExtension/project.yml"
  local project_dir="$ROOT/WidgetExtension/${WIDGET_EXTENSION_PROJECT_NAME}.xcodeproj"
  if command -v xcodegen >/dev/null 2>&1; then
    xcodegen generate --spec "$spec" --project "$ROOT/WidgetExtension" --quiet
  elif [[ ! -f "$project_dir/project.pbxproj" ]]; then
    echo "ERROR: Missing ${project_dir}; install xcodegen or restore the generated project." >&2
    exit 1
  fi
}

build_widget_extension() {
  local xcode_conf="Release"
  if [[ "$LOWER_CONF" == "debug" ]]; then
    xcode_conf="Debug"
  fi

  ensure_widget_extension_project

  local derived_dir="$ROOT/.build/xcode-widget-extension-${LOWER_CONF}"
  local project_dir="$ROOT/WidgetExtension/${WIDGET_EXTENSION_PROJECT_NAME}.xcodeproj"
  local build_log="$derived_dir/xcodebuild.log"
  local timeout_seconds="${CODEXBAR_WIDGET_EXTENSION_TIMEOUT_SECONDS:-900}"
  local archs="${ARCH_LIST[*]}"

  mkdir -p "$derived_dir"
  echo "Building ${WIDGET_PRODUCT_NAME} Xcode extension (${xcode_conf}, ${archs})." >&2
  xcodebuild \
    -project "$project_dir" \
    -scheme "$WIDGET_EXTENSION_SCHEME" \
    -configuration "$xcode_conf" \
    -destination "generic/platform=macOS" \
    -derivedDataPath "$derived_dir" \
    -skipPackageUpdates \
    -disableAutomaticPackageResolution \
    -skipMacroValidation \
    -skipPackagePluginValidation \
    CODEXBAR_WIDGET_BUNDLE_ID="$WIDGET_BUNDLE_ID" \
    CODEXBAR_TEAM_ID="$APP_TEAM_ID" \
    MARKETING_VERSION="$MARKETING_VERSION" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    CODE_SIGNING_ALLOWED=NO \
    ARCHS="$archs" \
    ONLY_ACTIVE_ARCH=NO \
    build >"$build_log" 2>&1 &

  local xcodebuild_pid=$!
  local elapsed=0
  while kill -0 "$xcodebuild_pid" 2>/dev/null; do
    if [[ "$elapsed" -ge "$timeout_seconds" ]]; then
      kill "$xcodebuild_pid" 2>/dev/null || true
      wait "$xcodebuild_pid" 2>/dev/null || true
      tail -80 "$build_log" >&2 || true
      echo "ERROR: Timed out building ${WIDGET_PRODUCT_NAME} extension after ${timeout_seconds}s" >&2
      exit 1
    fi
    sleep 5
    elapsed=$((elapsed + 5))
    if (( elapsed > 0 && elapsed % 60 == 0 )); then
      echo "Still building ${WIDGET_PRODUCT_NAME} extension (${elapsed}s)..." >&2
    fi
  done
  if ! wait "$xcodebuild_pid"; then
    tail -120 "$build_log" >&2 || true
    echo "ERROR: Failed to build ${WIDGET_PRODUCT_NAME} extension" >&2
    exit 1
  fi

  local appex="$derived_dir/Build/Products/${xcode_conf}/${WIDGET_PRODUCT_NAME}.appex"
  if [[ ! -f "$appex/Contents/MacOS/${WIDGET_PRODUCT_NAME}" ]]; then
    echo "ERROR: Missing Xcode-built ${WIDGET_PRODUCT_NAME}.appex at ${appex}" >&2
    exit 1
  fi
  echo "$appex"
}

install_widget_extension() {
  local src_appex
  src_appex="$(build_widget_extension)"
  local widget_app="$APP/Contents/PlugIns/${WIDGET_PRODUCT_NAME}.appex"
  rm -rf "$widget_app"
  mkdir -p "$APP/Contents/PlugIns"
  cp -R "$src_appex" "$widget_app"
  verify_binary_arches "$widget_app/Contents/MacOS/${WIDGET_PRODUCT_NAME}" "${ARCH_LIST[@]}"
}

install_binary "$APP_SWIFTPM_PRODUCT" "$APP/Contents/MacOS/${APP_EXECUTABLE_NAME}"
# Ship QuotaKitCLI alongside the app for easy symlinking.
if [[ -n "$(resolve_binary_path "$CLI_SWIFTPM_PRODUCT" "${ARCH_LIST[0]}")" ]]; then
  install_binary "$CLI_SWIFTPM_PRODUCT" "$APP/Contents/Helpers/${CLI_EXECUTABLE_NAME}"
fi
# Watchdog helper: ensures `claude` probes die when QuotaKit crashes/gets killed.
if [[ -n "$(resolve_binary_path "$WATCHDOG_SWIFTPM_PRODUCT" "${ARCH_LIST[0]}")" ]]; then
  install_binary "$WATCHDOG_SWIFTPM_PRODUCT" "$APP/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}"
fi
install_widget_extension
# Embed Sparkle.framework
if [[ -d ".build/$CONF/Sparkle.framework" ]]; then
  COPYFILE_DISABLE=1 cp -R ".build/$CONF/Sparkle.framework" "$APP/Contents/Frameworks/"
  chmod -R u+w "$APP/Contents/Frameworks/Sparkle.framework"
  install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP/Contents/MacOS/${APP_EXECUTABLE_NAME}"
  SPARKLE="$APP/Contents/Frameworks/Sparkle.framework"
if [[ "$SIGNING_MODE" == "adhoc" ]]; then
  CODESIGN_ID="-"
  CODESIGN_ARGS=(--force --sign "$CODESIGN_ID")
elif [[ "$ALLOW_LLDB" == "1" ]]; then
  CODESIGN_ID="-"
  CODESIGN_ARGS=(--force --sign "$CODESIGN_ID")
else
  if [[ -z "${APP_IDENTITY:-}" ]]; then
    echo "ERROR: Set APP_IDENTITY to a QuotaKit-owned Developer ID identity." >&2
    exit 1
  fi
  CODESIGN_ID="$APP_IDENTITY"
  if [[ "$CODESIGN_ID" == "Apple Development:"* ]]; then
    CODESIGN_ARGS=(--force --sign "$CODESIGN_ID")
  else
    CODESIGN_ARGS=(--force --timestamp --options runtime --sign "$CODESIGN_ID")
  fi
fi
CODESIGN_ARGS_NO_TIMESTAMP=(--force --options runtime --sign "${CODESIGN_ID}")
function resign() {
  xattr -cr "$1" 2>/dev/null || true
  if ! codesign "${CODESIGN_ARGS[@]}" "$1" 2>&1; then
    if [[ " ${CODESIGN_ARGS[*]} " == *" --timestamp "* ]]; then
      echo "  timestamp failed, retrying without timestamp: $1" >&2
      codesign "${CODESIGN_ARGS_NO_TIMESTAMP[@]}" "$1"
    else
      return 1
    fi
  fi
}

copy_app_bundle() {
  local source="$1"
  local destination="$2"
  rm -rf "$destination"
  mkdir -p "$(dirname "$destination")"
  ditto --noextattr --noqtn "$source" "$destination"
  xattr -cr "$destination" 2>/dev/null || true
}

seal_app_bundle_copy() {
  local bundle="$1"
  local sparkle="${bundle}/Contents/Frameworks/Sparkle.framework"
  local widget="${bundle}/Contents/PlugIns/${WIDGET_PRODUCT_NAME}.appex"

  if [[ "$SIGNING_MODE" == "adhoc" ]]; then
    xattr -cr "$bundle" 2>/dev/null || true
    if [[ -d "$sparkle" ]]; then
      resign "$sparkle"
      resign "$sparkle/Versions/B/Sparkle"
      resign "$sparkle/Versions/B/Autoupdate"
      resign "$sparkle/Versions/B/Updater.app"
      resign "$sparkle/Versions/B/Updater.app/Contents/MacOS/Updater"
      resign "$sparkle/Versions/B/XPCServices/Downloader.xpc"
      resign "$sparkle/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader"
      resign "$sparkle/Versions/B/XPCServices/Installer.xpc"
      resign "$sparkle/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer"
      resign "$sparkle/Versions/B"
      resign "$sparkle"
    fi

    if [[ -f "${bundle}/Contents/Helpers/${CLI_EXECUTABLE_NAME}" ]]; then
      resign "${bundle}/Contents/Helpers/${CLI_EXECUTABLE_NAME}"
    fi
    if [[ -f "${bundle}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}" ]]; then
      resign "${bundle}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}"
    fi

    if [[ -d "$widget" ]]; then
      resign "${widget}/Contents/MacOS/${WIDGET_PRODUCT_NAME}"
      codesign --force --sign - \
        --entitlements "$WIDGET_ENTITLEMENTS" \
        "$widget"
    fi

    codesign --force --sign - \
      --entitlements "$APP_ENTITLEMENTS" \
      "$bundle"
    return
  fi

  if [[ -d "$sparkle" ]]; then
    resign "$sparkle"
    resign "$sparkle/Versions/B/Sparkle"
    resign "$sparkle/Versions/B/Autoupdate"
    resign "$sparkle/Versions/B/Updater.app"
    resign "$sparkle/Versions/B/Updater.app/Contents/MacOS/Updater"
    resign "$sparkle/Versions/B/XPCServices/Downloader.xpc"
    resign "$sparkle/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader"
    resign "$sparkle/Versions/B/XPCServices/Installer.xpc"
    resign "$sparkle/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer"
    resign "$sparkle/Versions/B"
    resign "$sparkle"
  fi

  if [[ -f "${bundle}/Contents/Helpers/${CLI_EXECUTABLE_NAME}" ]]; then
    resign "${bundle}/Contents/Helpers/${CLI_EXECUTABLE_NAME}"
  fi
  if [[ -f "${bundle}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}" ]]; then
    resign "${bundle}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}"
  fi

  if [[ -d "$widget" ]]; then
    resign "${widget}/Contents/MacOS/${WIDGET_PRODUCT_NAME}"
    codesign "${CODESIGN_ARGS[@]}" \
      --entitlements "$WIDGET_ENTITLEMENTS" \
      "$widget"
  fi

  codesign "${CODESIGN_ARGS[@]}" \
    --entitlements "$APP_ENTITLEMENTS" \
    "$bundle"
}
  # Sign innermost binaries first, then the framework root to seal resources
  resign "$SPARKLE"
  resign "$SPARKLE/Versions/B/Sparkle"
  resign "$SPARKLE/Versions/B/Autoupdate"
  resign "$SPARKLE/Versions/B/Updater.app"
  resign "$SPARKLE/Versions/B/Updater.app/Contents/MacOS/Updater"
  resign "$SPARKLE/Versions/B/XPCServices/Downloader.xpc"
  resign "$SPARKLE/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader"
  resign "$SPARKLE/Versions/B/XPCServices/Installer.xpc"
  resign "$SPARKLE/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer"
  resign "$SPARKLE/Versions/B"
  resign "$SPARKLE"
fi

if [[ -f "$ICON_TARGET" ]]; then
  cp "$ICON_TARGET" "$APP/Contents/Resources/Icon.icns"
fi

# Bundle app resources (provider icons, etc.).
APP_RESOURCES_DIR="$ROOT/Sources/CodexBar/Resources"
if [[ -d "$APP_RESOURCES_DIR" ]]; then
  cp -R "$APP_RESOURCES_DIR/." "$APP/Contents/Resources/"
fi
if [[ ! -f "$APP/Contents/Resources/Icon-classic.icns" ]]; then
  echo "ERROR: Missing Icon-classic.icns in app bundle resources." >&2
  exit 1
fi

# SwiftPM resource bundles (e.g. KeyboardShortcuts) are emitted next to the built binary.
CODEXBAR_BINARY="$(resolve_binary_path "$APP_SWIFTPM_PRODUCT" "${ARCH_LIST[0]}")"
PREFERRED_BUILD_DIR="$(dirname "${CODEXBAR_BINARY:-$(build_product_path "$APP_SWIFTPM_PRODUCT" "${ARCH_LIST[0]}")}")"
shopt -s nullglob
SWIFTPM_BUNDLES=("${PREFERRED_BUILD_DIR}/"*.bundle)
shopt -u nullglob
if [[ ${#SWIFTPM_BUNDLES[@]} -gt 0 ]]; then
  for bundle in "${SWIFTPM_BUNDLES[@]}"; do
    bundle_name="$(basename "$bundle")"
    cp -R "$bundle" "$APP/Contents/Resources/"
  done
fi
if [[ ! -d "$APP/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle" ]]; then
  echo "ERROR: Missing KeyboardShortcuts SwiftPM resource bundle (Settings → Keyboard shortcut will crash)." >&2
  echo "Expected: ${PREFERRED_BUILD_DIR}/KeyboardShortcuts_KeyboardShortcuts.bundle" >&2
  exit 1
fi

# Ensure contents are writable before stripping attributes and signing.
chmod -R u+w "$APP"

# Strip extended attributes to prevent AppleDouble (._*) files that break code sealing
xattr -cr "$APP"
find "$APP" -name '._*' -delete

# Strip extended attributes again right before signing (Dropbox re-adds them continuously)
xattr -cr "$APP" 2>/dev/null || true
find "$APP" -name '._*' -delete 2>/dev/null || true

# Sign helper binaries if present
if [[ -f "${APP}/Contents/Helpers/${CLI_EXECUTABLE_NAME}" ]]; then
  resign "${APP}/Contents/Helpers/${CLI_EXECUTABLE_NAME}"
fi
if [[ -f "${APP}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}" ]]; then
  resign "${APP}/Contents/Helpers/${WATCHDOG_EXECUTABLE_NAME}"
fi

# Sign widget extension if present
if [[ -d "${APP}/Contents/PlugIns/${WIDGET_PRODUCT_NAME}.appex" ]]; then
  resign "${APP}/Contents/PlugIns/${WIDGET_PRODUCT_NAME}.appex/Contents/MacOS/${WIDGET_PRODUCT_NAME}"
  codesign "${CODESIGN_ARGS[@]}" \
    --entitlements "$WIDGET_ENTITLEMENTS" \
    "$APP/Contents/PlugIns/${WIDGET_PRODUCT_NAME}.appex"
fi

# Embed provisioning profile.
# REQUIRED for release + real-signed builds: app entitlements include
# com.apple.application-identifier, which AMFI checks at launch against
# the embedded profile. A bundle without this file passes codesign /
# spctl / notarization / stapler but fails to launch with "Launchd job
# spawn failed" (POSIX 163). Fail loud here instead of shipping a
# broken bundle that only breaks on the user's Mac.
PROVISION_PROFILE="$ROOT/Provisioning/QuotaKit_Dev.provisionprofile"
if [[ ! -f "$PROVISION_PROFILE" && -f "$ROOT/Provisioning/CodexBar_Dev.provisionprofile" ]]; then
  PROVISION_PROFILE="$ROOT/Provisioning/CodexBar_Dev.provisionprofile"
fi
if [[ "${CONF}" == "release" && "${SIGNING_MODE:-}" != "adhoc" ]]; then
  if [[ ! -f "$PROVISION_PROFILE" ]]; then
    echo "FATAL: provisioning profile not found at $PROVISION_PROFILE" >&2
    echo "" >&2
    echo "  This file is gitignored and local-only. In a worktree or fresh" >&2
    echo "  checkout, copy it from the main repo:" >&2
    echo "    cp -R <main-repo>/Provisioning $ROOT/" >&2
    echo "" >&2
    echo "  Without it the bundle ships missing Contents/embedded.provisionprofile" >&2
    echo "  and AMFI rejects the binary at launch (POSIX 163), even though" >&2
    echo "  codesign / spctl / notarization / stapler all pass." >&2
    exit 1
  fi
  cp "$PROVISION_PROFILE" "$APP/Contents/embedded.provisionprofile"
elif [[ -f "$PROVISION_PROFILE" ]]; then
  # Adhoc / debug builds: embed best-effort if available, do not fail.
  cp "$PROVISION_PROFILE" "$APP/Contents/embedded.provisionprofile"
fi

# Strip xattr one final time before signing the app bundle
xattr -cr "$APP" 2>/dev/null || true
find "$APP" -name '._*' -delete 2>/dev/null || true

# Finally sign the app bundle itself
codesign "${CODESIGN_ARGS[@]}" \
  --entitlements "$APP_ENTITLEMENTS" \
  "$APP"

if [[ -n "$STAGED_APP_PATH" ]]; then
  copy_app_bundle "$APP" "$STAGED_APP_PATH"
  seal_app_bundle_copy "$STAGED_APP_PATH"
  echo "Staged $STAGED_APP_PATH"
fi

if [[ -n "$INSTALL_APP_PATH" ]]; then
  copy_app_bundle "$APP" "$INSTALL_APP_PATH"
  seal_app_bundle_copy "$INSTALL_APP_PATH"
  echo "Installed $INSTALL_APP_PATH"
fi

# Move the signed app bundle from /tmp back to the project directory
copy_app_bundle "$APP" "$APP_FINAL"
rm -rf "$(dirname "$APP")"
APP="$APP_FINAL"
echo "Created $APP"
