import CloudKit
import Foundation

/// Parses CloudKit remote-notification payloads to identify whether they
/// correspond to one of our quota push zones. Used by the iOS
/// `UNNotificationServiceExtension` to decide whether to enrich the push with
/// provider data — and unit-testable independent of the extension target.
public enum QuotaZoneNotificationParser {
    /// Quota states the parser recognizes — must stay in lockstep with the
    /// states `QuotaTransitionSubscriptions` registers and the `state`
    /// strings Mac writes in `QuotaTransition` records.
    public enum QuotaState: String, Sendable, Equatable, CaseIterable {
        case depleted
        case restored
        /// iOS 1.6.0 / Mac 0.25.2 — pre-depletion warning at a
        /// configured threshold (e.g. 50% remaining).
        case warning
    }

    /// Returns `true` if the given zone is one of the quota push zones whose
    /// notifications we want the service extension to enrich.
    ///
    /// Supports both:
    /// - The Build 42–53 legacy global zones (`QuotaDepletedZone`,
    ///   `QuotaRestoredZone`) — kept so users who haven't re-run app launch
    ///   yet still get title rewrites.
    /// - The Build 54+ per-provider zones (`Quota-{providerID}-{state}Zone`)
    ///   generated by `QuotaProviderList.quotaZoneName`.
    public static func isQuotaPushZone(_ zoneID: CKRecordZone.ID) -> Bool {
        let name = zoneID.zoneName
        if name == CloudSyncConstants.quotaDepletedZoneName ||
            name == CloudSyncConstants.quotaRestoredZoneName
        {
            return true
        }
        return self.parseQuotaZoneName(name) != nil
    }

    /// Parses a per-provider zone name `"Quota-{providerID}-{state}Zone"`
    /// into its component providerID + state. Returns `nil` for legacy
    /// global zones or non-quota zones.
    ///
    /// **Format contract**: must match `QuotaProviderList.quotaZoneName(providerID:state:)`
    /// byte-for-byte. Any drift silently breaks NSE enrichment, which
    /// falls back to the static subscription alertBody — no regression
    /// but no title rewrite either.
    public static func parseQuotaZoneName(_ name: String) -> (providerID: String, state: QuotaState)? {
        guard name.hasPrefix("Quota-"), name.hasSuffix("Zone") else { return nil }
        let trimmed = String(name.dropFirst("Quota-".count).dropLast("Zone".count))
        // trimmed should be "{providerID}-{state}" — split on the LAST hyphen
        // so providerIDs containing a hyphen still parse correctly. None do
        // today (all UsageProvider raw values are single-token), but coding
        // defensively here costs nothing.
        guard let dashIndex = trimmed.lastIndex(of: "-") else { return nil }
        let providerID = String(trimmed[..<dashIndex])
        let stateString = String(trimmed[trimmed.index(after: dashIndex)...])
        guard let state = QuotaState(rawValue: stateString) else { return nil }
        guard !providerID.isEmpty else { return nil }
        return (providerID, state)
    }

    /// Parses a warning record's `recordName` into its component window +
    /// threshold. Returns `nil` if the format doesn't match.
    ///
    /// **Format contract**: matches
    /// `CloudSyncManager.writeQuotaWarningTransition`'s recordName
    /// template `"{providerID}-{window}-t{threshold}-{hourBucket}"`.
    /// Used by the iOS NSE to format the push body with the specific
    /// window + threshold without needing extra CKRecord fields.
    public static func parseWarningRecordName(
        _ recordName: String) -> (providerID: String, window: String, threshold: Int)?
    {
        // Split on `-`. Need at least 4 components: providerID-window-tN-hourBucket.
        // providerID itself could theoretically contain a hyphen but doesn't
        // today; assume the simple split is sufficient.
        let parts = recordName.split(separator: "-", omittingEmptySubsequences: false)
        guard parts.count >= 4 else { return nil }
        // Last component is hourBucket (integer), second-to-last is "tN"
        let thresholdPart = String(parts[parts.count - 2])
        guard thresholdPart.hasPrefix("t"),
              let threshold = Int(thresholdPart.dropFirst())
        else { return nil }
        let window = String(parts[parts.count - 3])
        let providerID = parts[0..<(parts.count - 3)].joined(separator: "-")
        guard !providerID.isEmpty, !window.isEmpty else { return nil }
        return (providerID, window, threshold)
    }

    /// Extracts the quota zone ID from a CloudKit remote-notification user-info
    /// dictionary. Returns `nil` if the payload isn't a `CKRecordZoneNotification`
    /// or the zone isn't one of our quota push zones (defensive against future
    /// zone additions, the legacy `QuotaTransitionsZone`, and non-CloudKit pushes).
    public static func extractQuotaZoneID(
        from userInfo: [AnyHashable: Any]) -> CKRecordZone.ID?
    {
        guard
            let notif = CKNotification(fromRemoteNotificationDictionary: userInfo),
            let zoneNotif = notif as? CKRecordZoneNotification,
            let zoneID = zoneNotif.recordZoneID,
            self.isQuotaPushZone(zoneID)
        else { return nil }
        return zoneID
    }
}
