// Generated by Scripts/regenerate-provider-manifests.sh. Do not edit by hand.

// First-party spellings keep call sites concise while their values remain validated instance IDs.
// swiftformat:disable sortDeclarations
extension ProviderInstanceID {
    public static let codex = UsageProvider.codex.instanceID
    public static let claude = UsageProvider.claude.instanceID
    public static let cursor = UsageProvider.cursor.instanceID
    public static let grok = UsageProvider.grok.instanceID
}

// swiftformat:enable sortDeclarations
