// Generated by Scripts/regenerate-provider-manifests.sh. Do not edit by hand.
import Foundation

/// Closed catalog of providers supported by this QuotaKit build.
public enum ProviderManifest {
    public static let allDescriptors: [ProviderDescriptor] = [
        CodexProviderDescriptor.descriptor,
        ClaudeProviderDescriptor.descriptor,
        CursorProviderDescriptor.descriptor,
        GrokProviderDescriptor.descriptor,
    ]
}
